### ISSUE TITLE
Track when user last visited project

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#1301]
**Describe the solution you'd like**
Track the date a user last visited a project, or a page related to app.

As a GovReady user, I'd like to know the when I last visited a project, so I can also find out what has changed since I visited.

**Describe alternatives you've considered**
Initial version could be the last time a user visited a project's main project page.

**Additional context**
This feature is useful to pull information from the database regarding what has changed since the visitor's last visit.

**Comment by YPCrumble** [comment]
@gregelin my proposal here would be a middleware that simply updates a field on the `User` model - something like `User.last_activity`*, each time a request from the user is processed. Something like this SO answer because it only updates the field once per hour instead of on every request: https://stackoverflow.com/a/55400572/2532070.

> Initial version could be the last time a user visited a project's main project page.

Could you show me a screenshot of where you'd want this shown on the frontend? I haven't built the app yet but might be fun for me to build out the middleware and finish this ticket from start to end as it's a simple one and would help me get the app built on my local.

As a next step it would be interesting to store feature release dates to show a user a list of new features on GovReady in a banner - something like this pseudo-model:

```
class GovReadyFeature(models.Model):
    """
    Model for documenting new feature releases on the GovReady platform.
    This model provides a date and description for features so that
    we can show users new features added since their `User.last_activity` datetime.
    """
    released = models.DateTimeField
    url_reverse_name = models.CharField  # not a URL field because this is internal
    short_description = models.CharField

    def get_banner_text(self):
        """
        Returns the link to the feature to be displayed to the user in a banner.
        (probably part of a template but here to show what I mean by `link_reverse_name` and `description`
        """
        link = reverse(self.url_reverse_name)
        return f'<a href="{{ link }}">{{ self.description }}</a>'
```

* Note that by default we know the last _login_ of a user via `User.last_login` - that's stored automatically by Django, but only when they are actually entering their user/pass. Depending on cookie lifetime this can be very much out of date.

**Comment by gregelin** [comment]
@YPCrumble
We were thinking of tracking last visit to the site _and_ last visit to an individual project. Tracking last visit to an individual project would help us share with user what has changed on the project since the individual last visited. Still thinking about whether it is worth tracking last visit to project (since I don't think GitHub tracks at that granularity).

For implementing the last visit to the site, I'd probably display that information `/projects` page as a small text.

BTW, the source code has changed since 2019. I recommend starting a new `venv` environment, and running `install-govready-q.sh` to install everything. Be sure to update Pip to ver 20+ before installing. Python 3.8 should work best right now, I think. Also, our MAC instructions have challenges, I'd let Ubuntu be a guide (but just use the SQLite database and not NGIXN etc.).
https://govready-q.readthedocs.io/en/latest/installation-and-setup/server-based-installation/linux/ubuntu/index.html

**Comment by gregelin** [comment]
Alternatively, before redesign things, you could just add to the user's drop down menu as a line item. That would show we have the data working.

**Comment by gregelin** [comment]
Will re-evaluate need
