### ISSUE TITLE
template rendering security issues

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#158]
Currently, the templates in the module YAML files are not aware of ACLs.  The templates can access anything. This is not a security issues as long as users cannot directly modify the module templates.

This becomes a risk when users can begin to modify templates and may have the ability to reference information that they would not otherwise have access.

**Comment by JoshData** [comment]
Adding to this issue some other considerations:

* Jinja2 template rendering uses safe mode, but we expose objects through the template context that might inadvertently and indirectly expose other data through their attributes (e.g. RenderedAnswer, RenderedProject, RenderedOrganization).

* CommonMark rendering of templates has safe mode turned off because we are intentionally using unsafe templates so we can embed raw HTML in some places. This could potentially be kept on for ModuleSources marked as trusted and turned off for the rest.

**Comment by gregelin** [comment]
@JoshData Has any of our recent work effected this issue?

**Comment by JoshData** [comment]
To clarify the original issue, templates can't access _anything_. They can only access user data, i.e. the set of question answers, that is for the project that is executing the template, plus other projects' data when projects are connected through answered questions. But we should continue to review the security implications of using Jinja2 templates.

To answer your question: No. It remains something for us to address if/when templates are authored by untrusted parties.

**Comment by gregelin** [comment]
No longer a security issue, because "templates can't access _anything_."

Closing due to age.

**Comment by JoshData** [comment]
Actually what I meant was the opposite - I was saying they can't access _just anything_, but they can potentially access any question answer beyond what the user loading the page could access. And I'm not sure where we left CommonMark safe mode in template rendering.
