### ISSUE TITLE
Change listening address from localhost to IP address

### ISSUE THREAD

**Issue by sijomc** [GovReady/govready-q#279]
Hi,

How can I change the listening address from localhost to IP address?
I have changed the same in ./siteapp/settings.py but it didn't help.
Please help me to resolve this.

Thanks in advance...

**Comment by JoshData** [comment]
Hello Sijo! Are you running Q using the instructions in the README or via Docker?

If you're using the README steps, in the last step where you run `python3 manage.py runserver`, you can instead run:

    python3 manage.py runserver 10.0.0.1:80

specifying an IP address and port.

Let me know if that helps!

**Comment by sijomc** [comment]
Hi JoshData,

Thanks for your reply. I followed instructions in the README and tried with "python3 manage.py runserver 192.168.1.166:8000". But when accessing through a browser it shows following error.

---------------------------------------
Request Method: | GET
-- | --
http://192.168.1.166:8000/
1.10.7
UnboundLocalError
local variable 'org' referenced before assignment
/opt/govready-q/siteapp/middleware.py in check_subdomain, line 133
/usr/bin/python3
3.4.3
['/opt/govready-q',  '/usr/lib/python3.4',  '/usr/lib/python3.4/plat-x86_64-linux-gnu',  '/usr/lib/python3.4/lib-dynload',  '/usr/local/lib/python3.4/dist-packages',  '/usr/lib/python3/dist-packages']
Mon, 24 Jul 2017 13:05:41 +0000
-------------------------------------

**Comment by JoshData** [comment]
Thanks. We still have some rough edges! Sorry about that.

Because Q is built for multi-tenant hosting of multiple organizations' sites, it uses the hostname in the HTTP request to determine which organization's Q site is being requested. There's a parent domain (e.g. localhost) and then subdomains for each organization (e.g. test.localhost).

If you change which IP address Python binds to, it'll be important to have a hostname and a subdoman aliased to that IP address. We usually modify our local `/etc/hosts` files to do this in testing by adding, e.g. for you:

    192.168.1.166 q
    192.168.1.166 myorg.q

Then when you visit `q` and `myorg.q` in your browser it'll find the right server and pass a logical hostname.

The hostname also has to be configured in a file we call `local/environment.json` (i.e.`environment.json`  in a subdirectory named `local` in the root of this project), for instance with:

    {
      "host": "q:8000",
      "organization-parent-domain": "q"
    }

The defaults are both localhost which is why it'll work out of the box if you visit `localhost` in your browser but didn't work for you when you changed the IP address.

Let me know if that helps.
