### ISSUE TITLE
Consistently show blank icons for unselected apps

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#420]
Unselected app areas should consistently show an "empty" icon and not show the app of a potentially matching icon. It's confusing to show the potential icon(s) b/c when there is only potential app it appears as if the application is already selected.

**Comment by JoshData** [comment]
We will revert the commit where I added automatic generation of icons.

**Comment by JoshData** [comment]
Discussion notes:

* This is hard because we're trying to convey the concept of abstraction in the UI --- i.e. if an app has not been started it's a slot for an abstract concept that needs to be filled in (choose a web server), vs if an app has been chosen that abstraction has been instantiated (you chose nginx).
* It's a lot of work to make icons for every abstraction that we need, and putting in the icon of a particular instance (nginx) may convey the wrong idea when an instance has not yet been chosen / the user may select a different instance.
* Is there even a finite/small set of protocols/icons to choose from? Can we create a directory of icons?
* The icon may be correlated with state --- the question is in an unstarted/empty state and action is required to activate it.
* The icon may be correlated with an expected action: When the user clicks, they will choose an app.

**Comment by gregelin** [comment]
We fixed this with the major UI changes for Kanban UI and card interface.
